spring.application.name=PROPERTYSERVICE
server.port=9092

spring.datasource.url=jdbc:postgresql://localhost:5432/property
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# AWS S3
aws.s3.bucket=springbucketbtm
aws.region=ap-south-1
aws.access-key=AKIAX2SWBDWEHXTKVAPB
aws.secret-key=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
