
spring.datasource.url= jdbc:postgresql://localhost:5432/property
spring.datasource.username=postgres
spring.dataSource.password=root
server.port=8082

spring.datasource.url= jdbc:postgresql://localhost:5432/property

spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.datasource.url= jdbc:postgresql://localhost:5432/property
spring.datasource.username=postgres
spring.dataSource.password=root
server.port=8082

spring.datasource.url= jdbc:postgresql://localhost:5432/property

spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




aws.s3.bucket=springbucketbtm

# AWS region (e.g., us-east-1, eu-west-1)
aws.region=ap-south-1

# AWS credentials (NOT recommended for production)
aws.access-key=AKIAX2SWBDWEHXTKVAPB
aws.secret-key=0GQUQtc1tazsHr/JvGHWX2REgzAVjvHCuCKu5IeW
